# https://taskfile.dev

version: "3"

dotenv:
  - .env

vars:
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'

tasks:
  default:
    cmds:
      - echo "$PYTHON"
      - echo "$WEBUI"
    silent: true

  launch:
    dir: "{{.WEBUI}}"
    cmds:
      - "{{.PYTHON}} launch.py --xformers --api --autolaunch"

  lint:
    cmds:
      - pre-commit run -a
